### ISSUE TITLE
plotly not support ggbio object

### ISSUE THREAD

**Issue by cj-forJ** [lawremi/ggbio#163]
Hi, it's very convenient to use ggbio, but how can i convert a ggbio object to a ggplot one? I want to show the results interactively using Plotly, thanks!

**Comment by sanchit-saini** [comment]
ggbio class has a slot for the ggplot object. Hence, it can be accessed with `@`.

For example
```R
ggbio_object@ggplot
```

**Comment by cj-forJ** [comment]
Thank you very much! The affair was settled. @sanchit-saini
